name: Test Build
on: 
  push:
    branches: 
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set WIP to Draft
      uses: wip/action@v1.0.0
    - uses: cachix/install-nix-action@v6
    - run: nix-build
